### ISSUE TITLE
Data getting deduplicated incorrectly and corrupting

### ISSUE THREAD

**Issue by nick-potts** [jacob-ebey/turbo-stream#36] opened 2024-07-03 09:34 UTC
I'm running single fetch and trying to pass back an object that has a bunch of deeply nested promises. each promise is similar, but different.

Each promise is suppose to return data in this format:
```
export type ReportMetricResponseDto = {
  id: string;
  name: string;
  value: number;
  formatted: string;
  errorMax: string;
  errorMin: string;
  errorPercentage: number;
  comparisonPercentage: number | null;
  positiveComparisonIsGood: boolean;
  inaccurateOrderCount: number;
  parentData: Modules.Reports.Dtos.ReportMetricParentData | null;
};
```

This is me just doing `JSON.stringify(data.formatted)`. It should just contain a string, but the turbo stream is somehow putting other metrics inside formatted.
<img width="529" alt="image" src="https://github.com/jacob-ebey/turbo-stream/assets/1109914/d25437a8-470a-4825-92f8-7007d4ed0660">

Some example scrambled data:
<img width="693" alt="image" src="https://github.com/jacob-ebey/turbo-stream/assets/1109914/f2b1d994-2909-4525-adec-35ace398d1b9">
<img width="718" alt="image" src="https://github.com/jacob-ebey/turbo-stream/assets/1109914/c58babec-b409-4a51-a67e-8a871197f02f">

If I `JSON.stringify` the promise's data, then decode it after the suspense resolves, it works perfectly fine.

**Comment by lsthornt** [comment] 2024-07-11 22:23
I am running into a corruption issue as well, but it's difficult to know if it's the same as what's happening with @nick-potts.

The data I am returning in my Remix loader looks like this:
```
  const foo = sleep(2000).then(() => 'foo');
  const bar = sleep(2000).then(() => 'bar');
  return { data: Promise.all([foo, bar]) };
```
 In the HTML body, I see the value seemingly correctly enqueued for hydration as `"P153:[[229,230],\"foo\",\"bar\"]\n"`.

However, once it gets to the `unflatten` phase of decoding, the indexes are off. Here is a screenshot of the debugger state during unflattening of this array:
<img width="500" alt="image" src="https://github.com/jacob-ebey/turbo-stream/assets/569689/757cc06b-6a34-4103-be42-7b62f40ca506">
In the data here, `parsed[0] = [229, 230]`, and startIndex is `229`. So, the array ends up recursively referencing itself. Once decoded, `data = [data, 'foo']`

I have found that this behavior is non-deterministic in my setup, and likely depends on the resolution order of multiple deferred Remix loaders. Reducing the `sleep` timeouts closer to zero (ensuring that this loader resolves first) generally reduces the failure rate.

I am still unsuccessful in creating a minimal reproduction of this case, but I'll eagerly add any information that would be helpful in resolving this issue

**Comment by jacob-ebey** [comment] 2024-08-10 16:41
Should be fixed.

**Closed by jacob-ebey** 2024-08-10 16:41 UTC
